services:
  - docker
sudo: false
language: java
jdk:
  - oraclejdk8
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - export LOG_HOME=/tmp/supernode && ./build/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Failed to report code coverage!"

cache:
  directories:
    - .autoconf
    - $HOME/.m2